best_parameters: {}
cv_results_summary:
  accuracy:
    mean: 0.9428967811911579
    std: 0.057085614925447614
  f1_weighted:
    mean: 0.9444598827117447
    std: 0.05320301272829893
  precision_weighted:
    mean: 0.9565115865100058
    std: 0.03166463637711848
  recall_weighted:
    mean: 0.9428967811911579
    std: 0.057085614925447614
final_metrics:
  accuracy: 0.7159090909090909
  auc: !!python/object/apply:numpy._core.multiarray.scalar
  - &id001 !!python/object/apply:numpy.dtype
    args:
    - f8
    - false
    - true
    state: !!python/tuple
    - 3
    - <
    - null
    - null
    - null
    - -1
    - -1
    - 0
  - !!binary |
    fWINd3m/6D8=
  f1_macro: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    QW9lkE4X3z8=
  f1_weighted: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    JfUf4FEO5j8=
  precision_macro: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    C4n7nkcP4j8=
  precision_weighted: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    6632qZvj5T8=
  recall_macro: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    42IXqgip3T8=
  recall_weighted: !!python/object/apply:numpy._core.multiarray.scalar
  - *id001
  - !!binary |
    6aKLLrro5j8=
model_type: RandomForestClassifier
target_classes:
- Closed
- Closed with explanation
- Closed with monetary relief
- Closed with non-monetary relief
- In progress
- Untimely response
training_date: '2025-09-09T18:24:25.928041'
